### ISSUE TITLE
Auto detect user email

### ISSUE THREAD

**Issue by Josee9988** [Josee9988/project-template#14]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

* Auto-detect the user email using the git cli

---

## **Describe the solution you'd like**

* To use the command `git config user.email`

---

### **Additional context**

* There would need to be added a 3rd script argument to change the mail

**Comment by Leeeooo19888** [comment]
> # **🚀 Feature Request**
> ## **Is your feature request related to a problem? Please describe.**
> * Auto-detect the user email using the git cli
> 
> ## **Describe the solution you'd like**
> * To use the command `git config user.email`
> 
> ### **Additional context**
> * There would need to be added a 3rd script argument to change the mail

E agora José ??

**Comment by Josee9988** [comment]
Please in English @Leeeooo19888 :D

**Comment by Leeeooo19888** [comment]
And now Yosef ?

**Comment by Leeeooo19888** [comment]
And Now ?

**Comment by Josee9988** [comment]
Hey @Leeeooo19888 , what do you want my friend?

**Comment by Leeeooo19888** [comment]
Nothing

**Comment by Josee9988** [comment]
@Leeeooo19888 then what are you posting here for? 🤣

**Comment by Leeeooo19888** [comment]
LoL

**Comment by Leeeooo19888** [comment]
.

**Comment by Leeeooo19888** [comment]
> .
