### ISSUE TITLE
Manage labels with .github/settings.yml

### ISSUE THREAD

**Issue by Josee9988** [Josee9988/project-template#17]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

* A .github/settings.yml file to manage project labels :D

---

## **Describe the solution you'd like**

* Something like [this](https://probot.github.io/apps/settings/)

**Comment by Leeeooo19888** [comment]
$ dig *WWW.EXAMPLE.COM <http://WWW.EXAMPLE.COM>* +nostats +nocomments +nocmd
    > ;*WWW.EXAMPLE.COM <http://WWW.EXAMPLE.COM>.*                     IN      A
    > *WWW.EXAMPLE.COM <http://WWW.EXAMPLE.COM>.*              3592
IN      CNAME   *YOUR-USERNAME*.github.io.
    > *YOUR-USERNAME*.github.io.      43192   IN      CNAME   *
GITHUB-PAGES-SERVER *.
    > * GITHUB-PAGES-SERVER *.         22      IN      A       192.0.2.1


Em qua., 14 de abr. de 2021 11:11 AM, Jose Gracia Berenguer <
***@***.***> escreveu:

**Comment by Josee9988** [comment]
@Leeeooo19888 hey, could you please stop commenting and creating nonsense posts and comments?
