### ISSUE TITLE
@Leeeooo19888 hey, could you please stop commenting and creating nonsense posts and comments?

### ISSUE THREAD

**Issue by Leeeooo19888** [Josee9988/project-template#18]
@Leeeooo19888 hey, could you please stop commenting and creating nonsense posts and comments?

_Originally posted by @Josee9988 in https://github.com/Josee9988/project-template/issues/17#issuecomment-819555338_

**Comment by Leeeooo19888** [comment]
I dont have money josef

**Comment by Josee9988** [comment]
Did I asked you for money or something? 😅💰 @Leeeooo19888

**Comment by Josee9988** [comment]
@Leeeooo19888 why do you open and close issues without any sense? Please don't do so!!

**Comment by Leeeooo19888** [comment]
Leeeooo19888
