### ISSUE TITLE
Tests_Runner.sh

### ISSUE THREAD

**Issue by murd4rp4rty** [Josee9988/project-template#53]
https://github.com/Josee9988/project-template/blob/8c6a188968d27324ab39afc11a3581337f08771c/tests/TESTS_RUNNER.sh#L9
# BASH_VERSION:  5.1.4(1)-release (x86_64-pc-linux-gnu)
will be shown as 5.1.4(0)-release (x86_64-pc-linux-gnu)

**Comment by Josee9988** [comment]
My bash version is what it is, the code is ok ;)
