### ISSUE TITLE
Waxaan ahay Adoon rabbi aaminsan kuna kalsoon rabbi xukumkisa

### ISSUE THREAD

**Issue by Salmanmuudey** [Josee9988/project-template#55]
# **🚀 Feature Request**

## **Is your feature request related to a problem? Please describe.**

*

---

## **Describe the solution you'd like**

*

---

## **Describe alternatives you've considered**

*

---

### **Additional context**

*

Waxaa jira dad diin sheeganaya misana dhaqankooda iyo diinta aysan is waafaqsan

**Comment by Salmanmuudey** [comment]
Hi josee how are you doing why you close my issue

**Comment by Josee9988** [comment]
What is your issue about? I could not understand it
