### ISSUE TITLE
docuementation about the settings.yaml

### ISSUE THREAD

**Issue by nicola-lunghi** [Josee9988/project-template#70]
Hi I saw the https://github.com/Josee9988/project-template/blob/master/.github/settings.yml file.
How this works?
I need to install something in my repo or it is supported by github by default?

Thanks,
Nick

**Comment by Josee9988** [comment]
Hi!
You have all these information in [this section](https://github.com/Josee9988/project-template#-used-github-bots) of the project's readme.

You do need the settings label bot.

Kind regards.

![image](https://github.com/Josee9988/project-template/assets/38838976/b7784b50-59c4-46a1-9c34-a2c8b3d5857f)
